---
name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release contains improvements and/or bug fixes.
          draft: false
          prerelease: false
